### ISSUE TITLE
Completed module 02 assignments

### ISSUE THREAD

**Issue by Bigabwamukama** [ds4owd-001/md-02-assignments-Bigabwamukama#1]
Hello @larnsce @mianzg @sskorik01 , I am happy to have completed my module 02 assignments. 
I would also like to ask about task 10 of scatterplot and faceting as it brought an error in inserting the size argument as population, thank you.

**Comment by sskorik01** [comment]
Hi, congratulation for completing and pushing your second assignment! What did you insert for the size argument?

**Comment by Bigabwamukama** [comment]
Hello, had left it out at first to skip the error but i researched on it and I am going to correct it.
